name: sauceDemo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
       -  name: Checkout repo
          uses: actions/checkout@v4

       -  name: Set up Node.js
          uses: actions/setup-node@v2
          with:
              node-version: '18'

       # -  name: Install Chrome
       #    run: |
       #      sudo apt-get update
       #      sudo apt-get install -y google-chrome-stable
       #      google-chrome --version

       # -  name: Install ChromeDriver
       #    run: npm install chromedriver --save-dev
            
       -  name: Install dependancies
          run: npm install
   
       -  name: Run tests
          run: npm run regression
